### ISSUE TITLE
Add instances for large words and ints

### ISSUE THREAD

**Issue by echatav** [iostat/relapse#6]
see my package [largeint](https://github.com/echatav/largeint)

**Comment by iostat** [comment]
As handy as this definitely would be (especially for people who'd use this for Ethereum which works with these kinds of values), I'd rather keep `relapse` itself as close to "stdlib" haskell as possible (i.e., `base` + ubiquitous libraries).

Perhaps a `relapse-largeint` package would be more appropriate containing extra instances?

**Comment by echatav** [comment]
Ewww. Orphans. I'm happy with fromInteger. You can go with 'instance Integral a => RLPEncodable a' and not incur a dependency. Or I can just use it where I need it.

**Comment by iostat** [comment]
Actually, thats a good point. We have all these hardcoded instances for `Int`, `Integer`, `Word*`. However, what actually operates on them is generalized to `Integral n, [Finite]Bits n`, Perhaps we should drop all the Int/Integer/etc. instances and make two general `Bits`/`FiniteBits` instances?

If LargeInt instantiates `Bits`/`FiniteBits` there's a great reason to implement that in relapse.

**Comment by echatav** [comment]
Yes

**Comment by iostat** [comment]
Resolved by #7
